### ISSUE TITLE
TODO 리스트 정리 입니다.

### ISSUE THREAD

**Issue by kimjinmyeong** [CH4-IS20/delivery-system#42]
# 필수 기능
- MSA 애플리케이션 구성
    - [x]  유레카 서버를 생성해서 모든 애플리케이션을 관리해주세요.
    - [x]  게이트웨이를 생성해서 게이트웨이가 모든 인입을 관리하게 해주세요.
    - [x]  API Gateway에 인증 및 권한 확인 로직을 추가하여 각 서비스로의 요청이 올바르게 인증된 사용자로부터만 이루어지도록 합니다.
    - [ ]  이번 과제는 MSA에 집중하기 위해, 서버 배포 없이 로컬 환경에서 구성하도록 합니다. 모든 애플리케이션을 Docker 컨테이너로 실행해주세요.
        - [ ]  Dockerfile *(혹은 docker-compose)* 파일을 작성하고 컨테이너로 실행후 동작을 확인해주세요.
- 모든 인원이 수행해야 하는 필수 과제
    - [ ]  Gemini API 연동
    - [ ]  각자 담당하는 애플리케이션에서 Gemini API를 연동하여 질문을 하고 답변을 받을 수 있도록 합니다.
    - [ ]  해당 질문과 답변은 모두 저장 되어야 합니다.
- 허브 관리
    - [x]  허브 엔티티를 생성해주세요. 필수 정보는 다음과 같습니다.
        - 허브 이름, 주소, 위도, 경도
    - [x]  허브 엔티티의 CRUD + Search를 구현해 주세요.
    - [x]  허브 엔티티에 is_delete 필드를 추가하여 논리적으로 삭제를 관리합니다. 허브 삭제 시, is_delete 필드를 true로 설정하며, 관련된 서비스에서 API 호출을 통해 해당 허브의 연관 데이터를 처리할 때도 이 필드를 기준으로 처리합니다.
    - [x]  모든 조회 및 검색에서 is_delete가 false인 데이터만을 대상으로 처리하도록 합니다.
    - [ ]  허브 정보가 자주 변경되지 않으며 반복적으로 조회될 가능성이 있음으로 허브 정보를 캐싱해주세요.
    - [x]  권한 관리는 아래와 같습니다.
        - **생성, 수정, 삭제**: 마스터 관리자만 가능
        - **조회 및 검색**: 모든 로그인 사용자가 가능
- 허브간 이동정보 관리
    - [x]  재귀적 관계 (혹은 계층적 데이터 모델링)을 통해, 허브 간 이동정보 경로를 모델링할 수 있는 엔티티를 생성해주세요.  필수 정보는 다음과 같습니다.
        - 출발 허브 ID, 도착 허브 ID, 소요시간, 이동 경로 전시명(Optional)
    - [x]  허브간 이동정보 엔티티에 is_delete 필드를 추가하여 논리적 삭제를 관리합니다. 허브가 삭제될 때 연관된 이동정보도 is_delete 필드를 통해 비활성화합니다.
    - [x]  모든 조회 및 검색에서 is_delete가 false인 데이터만을 대상으로 처리하도록 합니다.
    - [ ]  허브 간 이동 경로 정보는 자주 변하지 않는 데이터입니다. 이 정보를 캐싱하여, API 호출 빈도를 줄이고 빠르게 조회 될수 있도록 해주세요.
    - [x]  권한 관리는 아래와 같습니다.
        - **생성, 수정, 삭제**: 마스터 관리자 또는 스케줄러만 가능
        - **조회 및 검색**: 모든 로그인 사용자가 가능

- 배송담당자 관리
    - [x]  배송담당자 엔티티를 생성해주세요. 필수 정보는 다음과 같습니다.
        - 소속 허브 ID, slack ID, 배송담당자 타입(허브 이동 담당자, 업체 배송 담당자)
        - [ ]  타입이 허브 이동 담당자일 경우, 소속 허브 ID를 어떻게 해야할까요?
        - [x]  배송 담당자의 ID는 사용자 관리 엔티티의 사용자와 동일해야 합니다.(사용자 중에 배송 담담자가 있습니다.)
    - [ ]  배송 담당자가 추가 수정될때는 다음의 사항이 확인되어야 합니다.
        - [ ]  배송담당자 타입이 업체 배송 담당자인 경우*,* 소속 허브ID가 **존재하는 허브인지 확인합니다.
    - [x]  배송담당자 엔티티에 is_delete 필드를 추가하여 논리적 삭제를 관리합니다. 허브 정보가 삭제되거나 변경될 때, 해당 배송담당자 데이터도 is_delete 필드를 통해 관리합니다.
    - [x]  엔티티의 CRUD + Search를 구현해 주세요.
    - [ ]  권한 관리는 아래와 같습니다.
        - **마스터**: 모든 권한
        - **허브 관리자**: 본인 허브에 소속된 배송 담당자만 관리 가능
        - **배송 담당자 본인**: 자신의 정보만 확인 가능
        - **허브 소속 업체**: 해당 엔티티에 접근 권한 없음

- 업체 관리
    - [x]  업체 엔티티를 생성해주세요. 필수 정보는 다음과 같습니다.
        - 업체명, 업체 타입(생산업체, 수령업체), 업체 관리 허브 ID, 업체 주소
    - [x]  엔티티의 CRUD + Search를 구현해 주세요.
    - [ ]  업체가 추가, 수정될때는 다음의 사항이 확인되어야 합니다.
        - [ ]  관리 허브ID가 존재하는 허브인지 확인합니다.
    - [x]  업체 엔티티에 is_delete 필드를 추가하여 논리적 삭제를 관리합니다. 업체가 삭제될 경우 관련된 서비스에서 연관 데이터를 비활성화할 때 이 필드를 기준으로 처리합니다.
    - [x]  권한 관리는 아래와 같습니다.
        - **마스터**: 모든 권한
        - **허브 관리자**: 자신의 허브에 소속된 업체만 관리 가능
        - **허브 업체**: 자신의 업체만 수정 가능, 다른 업체의 읽기와 검색만 가능

- 상품 관리
    - [x]  상품 엔티티를 생성해주세요. 필수 정보는 다음과 같습니다.
        - 상품명, 업체 ID, 상품 관리 허브 ID
    - [x]  엔티티의 CRUD + Search를 구현해 주세요.
    - [x]  상품 엔티티에 is_delete 필드를 추가하여 논리적 삭제를 관리합니다. 상품이 삭제될 때 연관된 데이터(주문 등)도 is_delete 필드를 통해 관리합니다.
    - [x]  모든 조회 및 검색에서 is_delete가 false인 데이터만을 대상으로 처리하도록 합니다.
    - [ ]  상품 생성시에 다음이 확인되어야 합니다.
        - [x]  상품 업체가 존재하는지 확인합니다.
        - [ ]  상품 관리 허브 ID를 확인하여 존재하는지 확인합니다.
    - [x]  권한 관리는 아래와 같습니다.
        - **마스터**: 모든 권한
        - **허브 관리자**: 자신의 허브에 소속된 상품만 관리 가능
        - **허브 업체**: 자신의 업체의 상품만 생성 및 수정 가능
        - **기타 사용자**: 읽기와 검색만 가능

- 주문 관리
    - [x]  주문 엔티티를 생성해주세요. 필수 정보는 다음과 같습니다.
        - 요청업체 ID(공급업체), 수령 업체 ID, 상품 ID, 수량, 배송 ID
    - [x]  주문 엔티티에 is_delete 필드를 추가하여 논리적 삭제를 관리합니다. 주문이 취소되거나 삭제될 때 연관된 데이터도 is_delete 필드를 통해 관리합니다.
    - [x]  주문이 생성되면 배송도 같이 생성되어야합니다
    - [x]  권한 관리는 아래와 같습니다.
        - **생성**: 모든 로그인 사용자 (주문자) 가능
        - **수정**: 마스터 관리자와 해당 주문과   허브 관리자만 가능
        - **조회 및 검색**: 모든 로그인 사용자가 가능, 단, 주문자 본인은 자신의 주문만 조회 가능
- 배송 관리
    - [x]  배송 및 배송 경로 기록 엔티티에 is_delete 필드를 추가하여 논리적 삭제를 관리합니다. 배송과 관련된 모든 데이터에서 is_delete 필드를 기준으로 비활성화된 데이터를 관리합니다.
    - [x]  배송과 배송 경로 기록 엔티티를 생성해주세요. 필수 정보는 다음과 같습니다.
        - 배송 : 주문 ID, 현재상태(허브 대기중, 허브 이동중, 목적지 허브 도착, 배송중 등), 출발 허브 ID, 목적지 허브 ID, 배송지 주소, 수령인, 수령인 슬랙 ID(전화번호 대체)
        - 배송 경로 기록 : 배송 ID, 시퀀스(배송 경로 상 허브의 순번), 출발 허브 ID, 도착 허브 ID, 예상거리, 예상 소요시간, 실제 거리, 실제 소요 시간, 현재상태(허브 이동 대기중, 허브 이동중, 목적지 허브 도착, 배송중 등)
    - [x]  주문이 생성될때 배송과 배송 경로 기록 데이터가 같이 생성되어야 합니다.
    - [ ]  배송 경로는 최초에 모든 경로가 생성되어야 합니다.
    - [x]  권한 관리는 아래와 같습니다.
        - **생성**: 주문 생성 시 자동으로 생성
        - **수정**: 마스터 관리자, 해당 허브 관리자, 그리고 해당 배송 담당자만 가능
        - **조회 및 검색**: 모든 로그인 사용자가 가능, 단 배송 담당자는 자신이 담당하는 배송만 조회 가능

- 슬랙 메시지 관리
    - [x]  슬랙 메시지를 저장하는 엔티티를 생성합니다. 필수 정보는 다음과 같습니다.
        - 수신 ID, 메시지, 발송 시간등
    - [x]  슬랙 앱을 생성하고 API를 통해 메시지 발송 기능을 구현합니다.
    - [x]  권한 관리는 아래와 같습니다.
        - 로그인한 모든 사용자 및 내부 시스템은 발송 가능

- 사용자 관리
    - [x]  사용자 엔티티는 모든 사용자 정보를 관리합니다.
    - [x]  또한 다음의 권한으로 나누어 집니다.
        - 마스터 관리자
        - 허브 관리자
        - 허브 배송담당자
        - 허브 업체
    - [x]  회원가입 기능
        - [x]  유저의 이름, 패스워드를 전달 받아 회원가입을 진행합니다.
        - [x]  username은  `최소 4자 이상, 10자 이하이며 알파벳 소문자(a~z), 숫자(0~9)`로 구성
        - [x]  password는  `최소 8자 이상, 15자 이하이며 알파벳 대소문자(a~z, A~Z), 숫자(0~9), 특수문자`
    - [x]  로그인 기능
        - [x]  유저 아이디와 패스워드를 입력받아 로그인을 진행합니다.
        - [x]  로그인 성공 시, 로그인에 성공한 유저의 정보와 JWT를 활용하여 토큰을 발급합니다.
        - [x]  발급한 토큰을 사용하여 사용자 정보를 조회 해봅니다.
    - [x]  사용자 엔티티에 is_delete 필드를 추가하여 논리적 삭제를 관리합니다. 사용자가 삭제되거나 비활성화될 때 이 필드를 사용하여 처리합니다.
    - [x]  권한 관리는 아래와 같습니다.
        - 회원가입, 로그인 : 모두 접근 가능
        - **생성, 수정, 삭제**: 마스터 관리자만 가능
        - **조회 및 검색**: 사용자 본인만 자신의 정보를 조회 가능, 마스터 관리자는 모든 사용자 정보 조회 가능

- AI 연동 기능
    - [ ]  업체 배송 담당자에게 날씨와 배송 정보 알림 처리
        - [ ]  매일 아침 6시에 실행되는 스케줄러를 생성해주세요
        - [ ]  공공 데이터 포털의 날씨 API를 사용하여 해당일의 날씨 정보를 가져와 주세요.(https://www.data.go.kr/data/15084084/openapi.do)
        - [ ]  해당 날씨데이터와 기사가 배송해야 할 배송 정보를 Gemini API에 전달하여 요약 메시지를 생성하고 슬랙을 통해 발송 될 수 있게 해주세요.
    - [ ]  허브 배송 담당자에게 허브별 주문 사항에 대한 알림 처리
        - [ ]  아침 8시마다 허브 별 주문을 종합하여, 지금부터 로컬 시각 기준 24시간 이전 부터 현재 시각 까지 진행된 주문 건을 공통 허브 배송 담당자들에게 알려주는 slack 메시지를 전송해주세요. Gemini API를 사용하여 메시지를 생성해주세요.

- **기타 공통 사항**
    - [x]  서치에는 검색조건 및 정렬기능이 추가되어 있어야 합니다.
        - [x]  정렬기능은 기본적으로 생성일순, 수정일순을 기준으로 합니다.
    - [x]  서치 기능에는 10건, 30건, 50건 기준으로 페이지에 노출 될수 있습니다. 이외의 건수는 제한하여 기본 10건씩으로 고정합니다.
    - [ ]  모든 엔티티에서 is_delete 필드를 추가하여 논리적 삭제를 관리하며, 해당 필드가 false인 데이터만 조회 및 검색에서 사용되도록 로직을 구현합니다.
    - [ ]  DELETE 호출이 발생하면 각 서비스에서 삭제 대신 is_delete 필드를 true로 설정하여 데이터의 논리적 삭제를 수행합니다.
    - [ ]  트랜잭션 처리 시, 논리적 삭제에 대한 예외 상황도 고려하여 롤백 등의 처리를 구현합니다.
    - [ ]  MSA 환경에서 API 호출 기반으로 서비스 간 데이터 연관성을 유지하기 위해, 각 서비스 간에 필요한 연관 데이터를 처리하는 API를 제공하고, 데이터 변경 시 이를 즉시 반영할 수 있도록 서비스 간 통신을 설계해야 합니다.
    - [ ]  API 호출을 통해 서비스 간 데이터 동기화를 수행할 때, 실패 시 재시도 로직을 구현하여 통신의 신뢰성을 확보해야 합니다.
    - [ ]  서비스 간 데이터 일관성을 유지하기 위해 추가적인 로직을 구현해야 합니다.
    - [ ]  여러 개의 엔티티가 동시에 업데이트되거나 생성되는 경우 트랜잭션 처리를 구현해야 합니다. 예를 들어, 주문이 생성되면서 ~~재고와~~ 배송이 함께 관리될 때, 하나라도 실패하면 전체를 롤백하는 기능이 필요합니다.
    - [x]  테이블 명세서를 작성해주세요.
    - [x]  https://app.diagrams.net/ 또는 [https://dbdiagram.io/을](https://dbdiagram.io/%EC%9D%84) 통해 ERD를 만들어주세요.
    - [x]  https://app.diagrams.net/ 를 사용하여 인프라의 설계도를 작성해주세요.
    - [ ]  *Swagger를 적용하고 5단계 API 명세서 수준의 명세를 작성하고 개발 문서를 현행화 합니다.*
        - 마이크로 서비스별로 각개 구축이 기본입니다.
        - 게이트웨이를 통해 각 마이크로서비스의 문서를 전부 볼 수 있게 해주시면 베스트입니다.
    - [ ]  모든 서비스에 Zipkin을 사용하여 분산 추적을 가능하게 해주세요.
    - [ ]  Prometheus와 Grafana를 사용하여 애플리케이션 상태 모니터링 대시보드를 생성해주세요.

# 도전 과제

- [ ]  허브 이동시에 최적화 경로를 찾아보세요.
    - [ ]  Gemini API에 출발 허브 목적지 허브 및 허브간 이동정보 데이터를 전달하여 최적의 경유 허브를 선택할 수 있도록 합니다.
    - [ ]  이 경우, 기존 허브간 이동 정보 테이블을 활용하시거나 다른 모델링을 고민해보시고 최적화 경로를 저장하고 활용할 수 있는 설계를 고민해봅시다.
    
- [ ]  매일 업체 배송담당자에게 아침 6시 슬랙 알림을 발송해주세요.
    - [ ]  업체 배송담당자가 당일 방문해야 하는 주소들의 위경도 값을 AI를 통해, 경유지 순서를 지정해주세요.
    - [ ]  결과 경유지 순서를 사용하여 네이버 경로 API의 waypoints 파라미터를 사용하여 결과를 받아주세요.
        - [ ]  네이버 Map API 중 **Directions 5 API** 연동을 구현해주세요.(https://api.ncloud-docs.com/docs/ai-naver-mapsdirections-driving)
        - [ ]  경로 API는 위도와 경도 값으로 출발지와 도착지를 입력합니다. 다른 API를 사용하여 이름을 통해 위도 경도를 입력할 수 있지만 google 맵에서 검색하면 주소에 위경도 값이 나옵니다.
        
        ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/83c75a39-3aba-4ba4-a792-7aefe4b07895/9df5fb14-f829-43f7-bd0d-6de467389a92/image.png)
        
    
    - [ ]  해당 방문 순서를 포함한 경로 및 시간 데이터를 포함하여 AI를 통해 메시지를 생성하여 슬랙으로 발송해주세요.
    - [ ]  구현과 테스트 편의성을 위해 발송 시각을 설정파일에서 관리하고 수정할 수 있게 해주세요.

- [ ]  서비스에서 네이버 **경로 API를 사용할때 파라미터 값들이 필요한 경우, **서버 배포 없이 **변경이 자유롭게 만들어야 합니다.
    - [ ]  해당 값들을 저장하는 테이블을 만들고 엔티티를 생성해주세요.
    - [ ]  파라미터별 컬럼들을 나누어 레코드 하나에 저장해주세요. (fueltype,mileage 등을 저장합니다.)
    - [ ]  API호출 시 최신 레코드 1개에서 파라미터들을 가져와 API호출을 할 수 있도록 만들어주세요.
    
- [ ]  서비스 간 호출을 메시징 시스템으로 전환하기(모든 부분이 아닌 일부분 선택하여 전환해봅니다.)
    - [ ]  메시징 시스템 종류는 다양하며 대표적으로 Kafka와 RabbitMQ가 있습니다. 이외에도 다양한 메시징 시스템 중, 원하는 시스템을 선택해보세요.
    - [ ]  기존의 API 호출 기반 서비스 간 통신을 메시징 시스템으로 전환합니다.
    - [ ]  메시징 시스템을 사용하여 각 서비스 간 비동기적으로 메시지를 전송하고, 이벤트 기반 통신을 구현합니다.
    - [ ]  각 서비스에서 필요한 큐를 설정하고, 메시지 송수신 로직을 구현하여 데이터의 일관성과 신뢰성을 확보합니다.
    - [ ]  메시징 시스템을 사용하여 서비스 간의 느슨한 결합을 유지하면서도 확장성과 유연성을 강화할 수 있습니다.
    - [ ]  기존 API 호출에 대한 로직은 필요 시 백업으로 유지하거나, 메시징 시스템 기반으로 대체합니다.
    - [ ]  MSA에서 적용 해볼만한 곳을 파악해보시고 메시징 시스템으로 전환해보세요 (MSA 서비스 간 연계, 슬랙 메시지 발송 등등).

- [ ]  비밀번호 초기화(찾기) 기능만들기
    - [ ]  사용자 정보에 슬랙 아이디를 추가합니다. SMS 또는 Email 로 코드를 받는 부분을 Slack으로 대체 합니다.
    - [ ]  사용자의 아이디와 함께 비밀번호 초기화 검증을 요청하면 슬랙으로 난수를 전송합니다.
    - [ ]  사용자가 해당 난수를 확인하고 다시 아이디와 함께 초기화를 요청하면, 사용자의 비밀번호를 비밀번호 조건에 맞는 랜덤한 암호로 변경하고 저장, 응답합니다.
    - [ ]  비밀번호를 입력받고 수정하는 기능을 만들어 주세요.
    - [ ]  비밀번호 수정은 로그인 된 상태에서만 가능하게 해주세요.

- [ ]  그라파나 알람을 구현해주세요
    - [ ]  모니터링상 애플리케이션에 문제가 생기면(애플리케이션 다운을 예로들어 진행해주세요) Master 관리자가 알람을 수신할 수 있도록 해주세요.
